export const RouteObjects = {
  root: "/",
  Login: "/login",
  StudentDashboard: "/studentdash",
  FeeInvoice: "/feeinvoice",
  FeeStructure: "/feestructre",
  HomeWorks: "/homeworks",
  Payment: "/paymenthistory",
  StudyMaterials: "/studymaterials",
  StudentLibrary: "/studentlibrary",

  StaffDashboard: "/staffdash",
  Stafflibrary: "/stafflibrary",
  Bookmanagment: "/bookdetails/page",
  Issuebooks: "/issuedbookdetails",
  Issuecards: "/issuedcarddetails",
  LibrarySettings: "/librarysettings",
  StudentsList: "/studentlist/page",
  StudentProfile: "/studentprofile",
  AddStudent: "/addstudent",
  EditStudent: "/editstudent",
  RequireForms: "/forms",
  StudentsAttendance: "/students/attendance",
  StudentsAttendanceTable: "/students/attendancetable",
  StaffAttandanceTable:"/staff/attendancetable",
  StaffAttandance: "/staff/attendance",
  AttandanceReport: "/attendance/reports",
  StaffList: "/staffdetails",
  AddStaffList: "/Addstaff",
  EditStaffList: "/editstaff",
  StaffProfile: "/staffprofile",

  StaffManageClass: "/staff/manageclass",
  StaffAcademicsSettings: "/staff/academics/settings",

  StaffStudyRoom: "/staff/studyroom*",
  StudyRoomHome: "/staff/studyroom/home",
  StudyRoomHome2: "/staff/studyroom/rooms",

  StudentStudyRoom: "/student/studyroom*",
  StudentStudyRoomHome: "/student/studyroom/home",
  StudyRoom: "/student/studyroom/rooms",

  AdminStudentPage: "/admin/student",
  AllstudentsPage: "/admin/student/allstudents",

  ClasstimetablePage: "/staff/timetables/class",

  AdminHome: "/adminhome",
};
